name: GuildPlugin
version: 1.2.3
main: com.guild.GuildPlugin
api-version: '1.21'
authors: [chenasyd]
description: 一个功能完整的我的世界工会插件，支持Spigot和Folia
website: https://github.com/chenasyd
softdepend: [PlaceholderAPI, Vault]

# 支持的最低版本
load: POSTWORLD

# Folia支持标记
folia-supported: true

commands:
  guild:
    description: 工会系统主命令
    usage: /guild help
    aliases: [g, 工会]
    permission: guild.use
  guildadmin:
    description: 工会管理员命令
    usage: /guildadmin help
    aliases: [ga, 工会管理]
    permission: guild.admin

permissions:
  guild.use:
    description: 允许使用工会系统
    default: true
  guild.admin:
    description: 工会管理员权限
    default: op
  guild.create:
    description: 允许创建工会
    default: true
  guild.invite:
    description: 允许邀请玩家加入工会
    default: true
  guild.kick:
    description: 允许踢出工会成员
    default: true
  guild.promote:
    description: 允许提升工会成员
    default: true
  guild.demote:
    description: 允许降级工会成员
    default: true
  guild.delete:
    description: 允许删除工会
    default: op
  guild.sethome:
    description: 允许设置工会家
    default: true
  guild.home:
    description: 允许传送到工会家
    default: true
  guild.relation:
    description: 允许管理工会关系
    default: true
  guild.economy:
    description: 允许管理工会经济
    default: true
  guild.deposit:
    description: 允许向工会存入资金
    default: true
  guild.withdraw:
    description: 允许从工会取出资金
    default: true
  guild.transfer:
    description: 允许向其他工会转账
    default: true
